version: '3'

services:
  contact-manager-backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: backend
      restart: unless-stopped
      env_file: .env
      environment:
        - MONGO_USERNAME=$MONGO_USERNAME
        - MONGO_PASSWORD=$MONGO_PASSWORD
        - MONGO_CLUSTER=$MONGO_CLUSTER
      ports:
        - "8080:8080"
      volumes:
        - ./backend:/home/node/app/backend
        - /home/node/app/backend/node_modules

  contact-manager-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-prod
    container_name: frontend
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"

volumes:
  node_modules: