kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: contact-manager-frontend
spec:
  replicas: 2
  template:
    metadata:
      name: frontend
      labels:
        app: contact-manager
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: gcr.io/GKE_PROJECT/IMAGE:TAG
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
        command: ["nginx", "-g", "daemon off;"]
        ports:
        - name: frontend
          containerPort: 80