kind: Service
apiVersion: v1
metadata:
  name: contact-manager-frontend-service
spec:
  type: LoadBalancer
  loadBalancerIP: "34.74.102.29"
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    role: frontend