kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: contact-manager-backend-production
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: contact-manager
        role: backend
        env: production
    spec:
      containers:
      - name: backend
        image: gcr.io/contact-manager-265704/contact-manager-backend:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        command: ["npm", "start"]
        ports:
          - name: backend
            containerPort: 8080