kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: contact-manager-frontend
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: contact-manager
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: gcr.io/cloud-solutions-images/gceme:1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
        command: ["npm", "start"]
        ports:
        - name: frontend
          containerPort: 80