kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: contact-manager-frontend-production
spec:
  replicas:
  template:
    metadata:
      name: frontend
      labels:
        app: contact-manager
        role: frontend
        env: production
    spec:
      containers:
      - name: frontend
        image: gcr.io/contact-manager-265704/contact-manager-frontend:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
        command: ["nginx", "-g", "daemon off;"]
        ports:
        - name: frontend
          containerPort: 80