kind: Service
apiVersion: v1
metadat:
  name: contact-manager-frontend
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    role: backend
    app: contact-manager