kind: Service
apiVersion: v1
metadata:
  name: contact-manager-frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 34.107.210.190
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    role: frontend